#!/usr/bin/env bash
# The Bash script creates a PID file, displays a message indefinitely, and handles signals with specific actions. It displays different messages for SIGINT and SIGTERM, and removes the PID file before exiting.
PID_FILE="/var/run/myscript.pid"

echo $$ > "$PID_FILE"

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PID_FILE"; exit' SIGQUIT SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

